const gujaratRegions = [
  {
    district: "Ahmedabad",
    talukas: [
      "Ahmedabad City",
      "Daskroi",
      "Sanand",
      "Dholka",
      "Bavla",
      "Detroj-Rampura",
      "Mandal",
      "Viramgam",
      "Dhandhuka",
      "Barwala",
      "Ranpur",
    ],
  },
  {
    district: "Amreli",
    talukas: [
      "Amreli",
      "Babra",
      "Bagasara",
      "Dhari",
      "Jafrabad",
      "Khambha",
      "Kunkavav Vadia",
      "Lathi",
      "Lilia",
      "Rajula",
      "Savarkundla",
    ],
  },
  {
    district: "Anand",
    talukas: [
      "Anand",
      "Anklav",
      "Borsad",
      "Khambhat",
      "Petlad",
      "Sojitra",
      "Tarapur",
      "Umreth",
    ],
  },
  {
    district: "Aravalli",
    talukas: ["Bhiloda", "Malpur", "Meghraj", "Modasa", "Dhansura", "Bayad"],
  },
  {
    district: "Banaskantha",
    talukas: [
      "Palanpur",
      "Deesa",
      "Dhanera",
      "Danta",
      "Vadgam",
      "Amirgadh",
      "Bhabhar",
      "Deodar",
      "Kankrej",
      "Lakhani",
      "Suigam",
      "Tharad",
      "Vav",
    ],
  },
  {
    district: "Bharuch",
    talukas: [
      "Bharuch",
      "Ankleshwar",
      "Hansot",
      "Jambusar",
      "Jhagadia",
      "Netrang",
      "Vagra",
      "Valia",
      "Amod",
    ],
  },
  {
    district: "Bhavnagar",
    talukas: [
      "Bhavnagar",
      "Ghogha",
      "Sihor",
      "Talaja",
      "Gariadhar",
      "Palitana",
      "Vallabhipur",
      "Umrala",
      "Jesar",
      "Mahuva",
      "Botad",
    ],
  },
  {
    district: "Botad",
    talukas: ["Botad", "Barwala", "Ranpur", "Gadhada"],
  },
  {
    district: "Chhota Udaipur",
    talukas: [
      "Chhota Udaipur",
      "Jetpur Pavi",
      "Kavant",
      "Naswadi",
      "Sankheda",
      "Bodeli",
    ],
  },
  {
    district: "Dahod",
    talukas: [
      "Dahod",
      "Garbada",
      "Limkheda",
      "Devgadh Baria",
      "Dhanpur",
      "Fatepura",
      "Jhalod",
      "Sanjeli",
    ],
  },
  {
    district: "Dang",
    talukas: ["Ahwa", "Subir", "Waghai"],
  },
  {
    district: "Devbhoomi Dwarka",
    talukas: ["Khambhalia", "Kalyanpur", "Bhanvad", "Okhamandal"],
  },
  {
    district: "Gandhinagar",
    talukas: ["Gandhinagar", "Dehgam", "Kalol", "Mansa"],
  },
  {
    district: "Gir Somnath",
    talukas: [
      "Veraval",
      "Talala",
      "Sutrapada",
      "Kodinar",
      "Una",
      "Gir Gadhada",
    ],
  },
  {
    district: "Jamnagar",
    talukas: ["Jamnagar", "Dhrol", "Jodiya", "Kalavad", "Lalpur", "Jamjodhpur"],
  },
  {
    district: "Junagadh",
    talukas: [
      "Junagadh",
      "Bhesana",
      "Visavadar",
      "Mendarda",
      "Vanthali",
      "Manavadar",
      "Keshod",
      "Mangrol",
      "Malia",
      "Talala",
    ],
  },
  {
    district: "Kheda",
    talukas: [
      "Nadiad",
      "Mehmedabad",
      "Matar",
      "Kathlal",
      "Kapadvanj",
      "Balasinor",
      "Mahudha",
      "Thasra",
      "Galteshwar",
      "Vaso",
    ],
  },
  {
    district: "Kutch",
    talukas: [
      "Bhuj",
      "Abdasa",
      "Anjar",
      "Bhachau",
      "Gandhidham",
      "Lakhpat",
      "Mandvi",
      "Mundra",
      "Nakhatrana",
      "Rapar",
    ],
  },
  {
    district: "Mahisagar",
    talukas: [
      "Lunawada",
      "Santrampur",
      "Kadana",
      "Khanpur",
      "Balasinor",
      "Virpur",
    ],
  },
  {
    district: "Mehsana",
    talukas: [
      "Mehsana",
      "Becharaji",
      "Jotana",
      "Kadi",
      "Kheralu",
      "Satlasana",
      "Unjha",
      "Vadnagar",
      "Vijapur",
      "Visnagar",
    ],
  },
  {
    district: "Morbi",
    talukas: ["Morbi", "Maliya", "Tankara", "Wankaner"],
  },
  {
    district: "Narmada",
    talukas: ["Rajpipla", "Nandod", "Tilakwada", "Dediapada", "Sagbara"],
  },
  {
    district: "Navsari",
    talukas: [
      "Navsari",
      "Jalalpore",
      "Gandevi",
      "Chikhli",
      "Vansda",
      "Khergam",
    ],
  },
  {
    district: "Panchmahal",
    talukas: [
      "Godhra",
      "Kalol",
      "Halol",
      "Jambughoda",
      "Ghoghamba",
      "Morva Hadaf",
      "Shahera",
    ],
  },
  {
    district: "Patan",
    talukas: [
      "Patan",
      "Saraswati",
      "Sidhpur",
      "Chanasma",
      "Harij",
      "Radhanpur",
      "Sami",
      "Santalpur",
    ],
  },
  {
    district: "Porbandar",
    talukas: ["Porbandar", "Ranavav", "Kutiyana"],
  },
  {
    district: "Rajkot",
    talukas: [
      "Rajkot",
      "Dhoraji",
      "Gondal",
      "Jamkandorna",
      "Jasdan",
      "Jetpur",
      "Kotda Sangani",
      "Lodhika",
      "Paddhari",
      "Upleta",
      "Vinchiya",
    ],
  },
  {
    district: "Sabarkantha",
    talukas: [
      "Himmatnagar",
      "Prantij",
      "Talod",
      "Khedbrahma",
      "Vijaynagar",
      "Vadali",
      "Idar",
    ],
  },
  {
    district: "Surat",
    talukas: [
      "Surat City",
      "Chorasi",
      "Kamrej",
      "Mandvi",
      "Mahuva",
      "Mangrol",
      "Olpad",
      "Palsana",
      "Bardoli",
      "Umarpada",
    ],
  },
  {
    district: "Surendranagar",
    talukas: [
      "Wadhwan",
      "Chotila",
      "Muli",
      "Sayla",
      "Chuda",
      "Thangadh",
      "Lakhtar",
      "Limbdi",
      "Dhrangadhra",
      "Dasada",
    ],
  },
  {
    district: "Tapi",
    talukas: ["Vyara", "Songadh", "Valod", "Nizar", "Uchchhal", "Dolvan"],
  },
  {
    district: "Vadodara",
    talukas: [
      "Vadodara City",
      "Vadodara",
      "Dabhoi",
      "Karjan",
      "Padra",
      "Savli",
      "Sinor",
      "Vaghodia",
      "Desar",
    ],
  },
  {
    district: "Valsad",
    talukas: ["Valsad", "Pardi", "Umbergaon", "Kaprada", "Dharampur", "Vapi"],
  },
];

module.exports = gujaratRegions;
